const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.join(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(__dirname,p),'utf8').replace(/^\uFEFF/,''));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const tests=read('p3-test-results.json'),review=read('p3-independent-results.json');
const files=['polished.html','polished.css','polished.js','polished-avatars.js','prototype-review.html'].map(p=>{const b=fs.readFileSync(path.join(root,p));return{path:p,sha256:sha(b),bytes:b.length};});
if(!tests.candidateStable||tests.checks.some(c=>c.status!=='PASS')||files.some(f=>(f.path==='polished.js'?tests.runtimeEnd:tests.candidateEnd[f.path])!==f.sha256))throw Error('Root evidence is failing or stale.');
const reviewEnd=review.candidateEnd||review.sourceEnd||review.hashesEnd;
if(!review.candidateStable||review.checks.some(c=>c.status!=='PASS')||files.some(f=>reviewEnd[f.path]!==f.sha256))throw Error('Independent evidence is failing or stale.');
const candidate='P3-'+sha(JSON.stringify(files)).slice(0,12),capturedAt=new Date().toISOString();
const scope='Local frontend prototype. Avatar uploads stay in this browser; Generate makes procedural variations. No live AI, authentication or browser/computer execution.';
const manifest={candidateId:candidate,capturedAt,baseline:'F08 / feedback-08.md',sources:files,tests:'.intentgraph/p3-test-results.json',independentReview:'.intentgraph/p3-independent-results.json',userApproval:'pending',scope};
fs.writeFileSync(path.join(__dirname,'polished-candidate.json'),JSON.stringify(manifest,null,2));
const evidence={candidate,capturedAt,scope,checks:tests.checks.map(c=>({name:c.name,status:c.status,detail:'Executed against this stable candidate; local interactions only.',evidence:'.intentgraph/p3-test-results.json'})).concat([{name:'Independent profile, identity and visual review',status:'PASS',detail:'See the separate reviewer’s exact checked scope and screenshots.',evidence:'.intentgraph/p3-independent-results.json'},{name:'Your visual decision',status:'PENDING',detail:'All requested local controls are ready to review. Final appearance and experience remain your decision.',evidence:'.intentgraph/feedback-08.md'}]),captures:[{label:'Main view',path:'.intentgraph/p3-theme-dark.png'},{label:'Light appearance',path:'.intentgraph/p3-theme-light.png'},{label:'Create agent',path:'.intentgraph/p3-create-agent.png'},{label:'Profile and avatars',path:'.intentgraph/p3-independent-profile.png'},{label:'Feedback task list',path:'.intentgraph/feedback-08.md'},{label:'Candidate manifest',path:'.intentgraph/polished-candidate.json'}]};
fs.writeFileSync(path.join(__dirname,'polished-evidence.json'),JSON.stringify(evidence,null,2));
const index=read('code-index.json');index.capturedAt=capturedAt;index.baseline='F08 P3 corrections; prior candidates retained';index.approval='P3 technical checks passed; user visual decision pending';index.coverage='Manual file and evidence index. No live code graph or agent telemetry.';index.polishedCandidate=candidate;
const entries=['polished-avatars.js','.intentgraph/feedback-08-original.txt','.intentgraph/feedback-08.md','.intentgraph/p3-test-results.json','.intentgraph/p3-independent-results.json'];
for(const p of entries){const abs=path.join(root,p);if(!index.nodes.some(n=>n.path===abs))index.nodes.push({id:p,type:p.endsWith('.js')?'file':'record',path:abs});}
for(const n of index.nodes){if(n.path&&fs.existsSync(n.path)&&fs.statSync(n.path).isFile()){const b=fs.readFileSync(n.path);n.sha256=sha(b);n.bytes=b.length;}}
for(const edge of [{source:'polished.html',target:'polished-avatars.js',relation:'loads-avatar-module'},{source:'.intentgraph/feedback-08.md',target:'polished.js',relation:'specifies-interactions'},{source:'.intentgraph/feedback-08.md',target:'polished.css',relation:'specifies-appearance'},{source:'.intentgraph/p3-test-results.json',target:'polished.html',relation:'checks-candidate'},{source:'.intentgraph/p3-independent-results.json',target:'polished.html',relation:'independently-reviews-candidate'}]){if(!index.edges.some(e=>e.source===edge.source&&e.target===edge.target&&e.relation===edge.relation))index.edges.push(edge);}
fs.writeFileSync(path.join(__dirname,'code-index.json'),JSON.stringify(index,null,2));
console.log(JSON.stringify({candidate,rootChecks:tests.checks.length,independentChecks:review.checks.length,scope},null,2));
