const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true,ignoreDefaultArgs:['--headless'],args:['--headless=new']});
try{
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8767/intent-map.html');
await page.getByRole('button',{name:'Create agent from sidebar',exact:true}).click();
await page.getByLabel('Agent name',{exact:true}).fill('Firewall specialist');await page.getByLabel('What should this agent help with?',{exact:true}).fill('Inspect policies');
await page.getByRole('button',{name:'Create agent',exact:true}).click();await page.getByRole('button',{name:'Close settings',exact:true}).click();
await page.getByRole('button',{name:'Create chat, channel, project or agent',exact:true}).click();await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Lab Upgrade');await page.getByRole('button',{name:'Create project',exact:true}).click();
await page.getByRole('button',{name:'+ New channel',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('firewalls');await page.getByRole('button',{name:'Create channel',exact:true}).click();
await page.getByRole('button',{name:'+ New thread',exact:true}).click();
await page.locator('#recipient-summary').click();await page.getByLabel('Network companion',{exact:true}).check();
await page.getByRole('textbox',{name:'Wireframe message',exact:true}).fill('Review access policies');await page.getByRole('button',{name:'Preview sending message',exact:true}).click();
assert.match(await page.locator('#conversation').innerText(),/To Network companion, Firewall specialist/);
await page.getByRole('textbox',{name:'Wireframe message',exact:true}).fill('First thread draft');await page.getByRole('button',{name:'New chat',exact:true}).click();
assert.match(await page.locator('#chat-location').innerText(),/Lab Upgrade.*firewalls/);
await page.getByRole('textbox',{name:'Wireframe message',exact:true}).fill('Second thread draft');
await page.getByRole('button',{name:'Channels',exact:true}).click();assert.equal(await page.locator('#composer').isVisible(),false);
await page.getByRole('button',{name:'# firewalls 2 threads',exact:true}).click();
await page.getByRole('button',{name:'Review access policies 1 local messages',exact:true}).click();
assert.equal(await page.locator('#draft').inputValue(),'First thread draft');
await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('searchbox',{name:'Search workspace',exact:true}).fill('access');
await page.getByRole('button',{name:'Chat · Review access policies',exact:true}).click();
assert.equal(await page.locator('#draft').inputValue(),'First thread draft');
await page.reload();assert.equal(await page.locator('#draft').inputValue(),'First thread draft');
await page.getByRole('button',{name:'Channels',exact:true}).click();await page.getByRole('button',{name:'# firewalls 2 threads',exact:true}).click();await page.getByRole('button',{name:'New chat 0 local messages',exact:true}).click();
assert.equal(await page.locator('#draft').inputValue(),'Second thread draft');assert.doesNotMatch(await page.locator('#conversation').innerText(),/Review access policies/);
await page.getByRole('button',{name:'Add attachments or tools',exact:true}).click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Attach files',exact:true}).click();await(await chooser).setFiles({name:'thread-two.txt',mimeType:'text/plain',buffer:Buffer.from('fixture')});
await page.getByRole('button',{name:'Channels',exact:true}).click();await page.getByRole('button',{name:'# firewalls 2 threads',exact:true}).click();await page.getByRole('button',{name:'Review access policies 1 local messages',exact:true}).click();assert.equal(await page.locator('.attachment-chip').count(),0);
await page.getByRole('button',{name:'Channels',exact:true}).click();await page.getByRole('button',{name:'# firewalls 2 threads',exact:true}).click();await page.getByRole('button',{name:'New chat 0 local messages',exact:true}).click();assert.equal(await page.locator('.attachment-chip').count(),1);
await page.setViewportSize({width:390,height:844});const r=await page.locator('.canvas').boundingBox();assert(r.x+r.width<=390);
await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Open agent workspace',exact:true}).click();await page.screenshot({path:'.intentgraph/conversations-v06.png'});
assert.deepEqual(errors,[]);console.log('PASS: sidebar creation, project/channel/thread hierarchy, multi-agent recipients, thread isolation, drafts/reload, search, per-chat attachments, narrow canvas, no browser errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
