(() => {
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let token='',data={},state={},pageId=null,windows=[],controls=[],pendingApproval=null,busy=false,runSignature='';
  function notice(text){$('execution-notice').hidden=!text;$('execution-notice').textContent=text;}
  async function api(route,body){const r=await fetch('/api/'+route,{...(body?{method:'POST',headers:{'Content-Type':'application/json','X-IntentGraph-Token':token},body:JSON.stringify(body)}:{})});const value=await r.json();if(!r.ok)throw Error(value.error||'Operation failed');return value;}
  async function act(type,args={}){const value=await api('action',{type,...args});return value.result;}
  async function perform(fn){try{notice('Working…');const result=await fn();notice('');await refresh();return result;}catch(e){notice(e.message);return null;}}
  async function adapter(type,args={}){const result=await act('execution.adapter',{operation:{type,...args}});showTool(result);return result;}
  function showTool(result){$('adapter-output').textContent=JSON.stringify(result,null,2);const file=result?.screenshotPath;$('adapter-image').hidden=!file;if(file)$('adapter-image').src='/api/execution/artifact?path='+encodeURIComponent(file);}
  function dialog(title,html,onApprove,label='Approve this action'){$('execution-dialog-title').textContent=title;$('execution-dialog-body').innerHTML=html;$('execution-dialog-error').textContent='';$('approve-execution').textContent=label;pendingApproval=onApprove;$('execution-dialog').showModal();}
  $('approve-execution').onclick=async()=>{const button=$('approve-execution');button.disabled=true;try{await pendingApproval?.();$('execution-dialog').close();await refresh();}catch(e){$('execution-dialog-error').textContent=e.message;}finally{button.disabled=false;}};
  function runs(){return Array.isArray(data.coordinator)?data.coordinator:data.coordinator?.runs||[];}
  function renderRuns(){const items=runs(),signature=JSON.stringify(items);$('run-count').textContent=items.length+' runs';if(signature===runSignature)return;runSignature=signature;const feedback=new Map([...document.querySelectorAll('[data-feedback-text]')].map(n=>[n.dataset.feedbackText,n.value]));$('execution-runs').innerHTML=items.map(run=>{const id=run.id||run.runId,phase=run.status||run.phase||run.state||'unknown',proposal=run.pendingProposal||run.proposal;return `<article class="run-entry"><h3>${esc(run.title||state.tasks?.find(t=>t.id===run.taskId)?.title||run.taskId||id)}</h3><span class="run-state">${esc(phase)}</span><br><small>${esc(id)} · ${esc(run.model||'mimo-v2.5')} · ${esc(run.calls??run.budget?.calls??0)} calls</small>${(run.error||run.engineReviewPending)?'<p>'+esc(run.engineReviewPending?'Review submission pending: '+JSON.stringify(run.engineReviewPending):typeof run.error==='string'?run.error:run.error.message||JSON.stringify(run.error))+'</p>':''}${proposal?`<details><summary>Proposed changes</summary><pre>${esc(JSON.stringify(proposal,null,2))}</pre></details>`:''}${run.reviews?`<details><summary>Review findings</summary><pre>${esc(JSON.stringify(run.reviews,null,2))}</pre></details>`:''}<div class="toolbar-actions">${proposal&&/proposal|apply|approval/.test(phase)?`<button data-apply-run="${esc(id)}">Review & apply proposal</button>`:''}${/interrupted|blocked|paused/.test(phase)?`<button data-resume-run="${esc(id)}">Resume run</button>`:''}${!/completed|cancelled|failed|awaiting.owner|finished/.test(phase)?`<button data-cancel-run="${esc(id)}">Stop run</button>`:''}</div><label>Feedback for this run<textarea data-feedback-text="${esc(id)}" placeholder="Describe the correction or clarify the intent"></textarea></label><button data-send-run="${esc(id)}">Send feedback to the team</button></article>`;}).join('')||'<p class="empty">No run started. Choose a task with an approved baseline.</p>';for(const [id,value] of feedback){const field=document.querySelector('[data-feedback-text="'+CSS.escape(id)+'"]');if(field)field.value=value;}
    document.querySelectorAll('[data-apply-run]').forEach(button=>button.onclick=()=>{const run=items.find(r=>(r.id||r.runId)===button.dataset.applyRun);dialog('Review the proposed file changes',`<p>These changes apply only to the run’s original file scope. The service will reject them if the files or baseline have changed.</p><pre>${esc(JSON.stringify(run.pendingProposal||run.proposal,null,2))}</pre>`,()=>act('execution.run.apply',{runId:button.dataset.applyRun}),'Apply these changes');});
    document.querySelectorAll('[data-cancel-run]').forEach(b=>b.onclick=()=>perform(()=>act('execution.run.cancel',{runId:b.dataset.cancelRun})));
    document.querySelectorAll('[data-resume-run]').forEach(b=>b.onclick=()=>perform(()=>act('execution.run.resume',{runId:b.dataset.resumeRun})));
    document.querySelectorAll('[data-send-run]').forEach(b=>b.onclick=()=>perform(async()=>{const field=document.querySelector('[data-feedback-text="'+CSS.escape(b.dataset.sendRun)+'"]');if(!field.value.trim())throw Error('Write the feedback first');const result=await act('execution.run.feedback',{runId:b.dataset.sendRun,text:field.value});field.value='';return result;}));
  }
  async function refresh(){if(busy)return;busy=true;try{[data,state]=await Promise.all([api('execution'),api('state')]);const provider=data.provider||{},connected=provider.last?.ok||provider.lastConnection?.ok;$('provider-status').textContent=connected?'Connected · last request succeeded':provider.credentialStored?'Credential stored · ready to test or run':'Credential not configured';$('execution-connection').textContent='Local execution service';$('execution-connection').className='connection live';const selected=$('execution-task').value;$('execution-task').innerHTML=(state.tasks||[]).map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('')||'<option value="">Create a task in Code & team first</option>';if(selected&&state.tasks?.some(t=>t.id===selected))$('execution-task').value=selected;const a=data.adapters||{};pageId??=a.browser?.pages?.[0]?.pageId;$('browser-status').textContent=a.browser?.connected?'Owned browser connected':a.browser?.available?'Installed · ready to open an isolated browser':'Browser runtime unavailable';$('desktop-status').textContent=a.desktop?.selectedWindow?'Selected: '+a.desktop.selectedWindow.title:a.desktop?.available?'Installed · choose a window to inspect':'Windows adapter unavailable';$('network-status').textContent=a.network?.profileCount?'Read-only profiles configured':a.network?.available?'Adapter installed · Cisco session details still required':'Network adapter unavailable';$('delivery-status').textContent=(data.delivery?.catalog?.pinned&&data.delivery?.service?.available&&data.delivery?.service?.rootMatches)?(data.delivery?.git?.isRepository?'Trusted checks ready · Git repository detected':'Trusted checks ready · merge unavailable until a Git repository is selected'):'Check setup needs attention: '+(data.delivery?.reasons||[]).join(' · ');renderRuns();}catch(e){notice(e.message);$('execution-connection').textContent='Service unavailable';}finally{busy=false;}}
  $('run-form').onsubmit=e=>{e.preventDefault();perform(()=>act('execution.run.start',{taskId:$('execution-task').value}));};
  $('check-provider').onclick=()=>perform(()=>act('execution.provider.check'));
  $('refresh-execution').onclick=refresh;
  $('run-build').onclick=()=>perform(async()=>{const result=await act('execution.delivery.run',{taskId:$('execution-task').value,commandId:'verify-intentgraph'});showTool(result);return result;});
  $('open-owned-browser').onclick=()=>perform(async()=>{const result=await adapter('browser.open',{url:$('browser-url').value});pageId=result.pageId;return adapter('browser.inspect',{pageId});});
  $('inspect-owned-browser').onclick=()=>perform(()=>adapter('browser.inspect',{pageId}));
  $('preview-browser').onclick=()=>perform(async()=>{const result=await adapter('browser.preview',{pageId,kind:$('browser-kind').value,selector:$('browser-selector').value,...($('browser-kind').value==='fill'?{text:$('browser-text').value}:{})});dialog('Approve this browser interaction',`<pre>${esc(JSON.stringify(result.detail,null,2))}</pre><p>This permission expires shortly and applies once to this exact action.</p>`,()=>adapter('browser.execute',{approvalId:result.approvalId}));});
  $('list-windows').onclick=()=>perform(async()=>{const result=await adapter('desktop.windows');windows=result.windows||[];$('desktop-window').innerHTML=windows.map((w,i)=>`<option value="${i}">${esc(w.title)} · PID ${esc(w.pid)}</option>`).join('')||'<option value="">No accessible windows</option>';});
  $('inspect-desktop').onclick=()=>perform(async()=>{const selected=windows[Number($('desktop-window').value)];if(!selected)throw Error('List and select a window first');await adapter('desktop.select',selected);const result=await adapter('desktop.inspect');controls=result.controls||[];$('desktop-control').innerHTML=controls.map((c,i)=>`<option value="${i}">${esc(c.controlKind)} · ${esc(c.title||c.automationId||'Unnamed')}</option>`).join('')||'<option value="">No accessible controls</option>';return result;});
  $('preview-desktop').onclick=()=>perform(async()=>{const c=controls[Number($('desktop-control').value)];if(!c)throw Error('Inspect and select a control first');const targetControl={controlKind:c.controlKind,title:c.title,...(c.automationId?{automationId:c.automationId}:{}),...(c.className?{className:c.className}:{})};const result=await adapter('desktop.preview',{kind:$('desktop-kind').value,targetControl,...($('desktop-kind').value==='fill'?{text:$('desktop-text').value}:{})});dialog('Approve this desktop interaction',`<pre>${esc(JSON.stringify(result.detail,null,2))}</pre><p>This permission applies once to the selected window and control.</p>`,()=>adapter('desktop.execute',{approvalId:result.approvalId}));});
  $('read-network').onclick=()=>perform(async()=>{const id=$('network-profile').value;if(!id)throw Error('A verified Cisco sandbox profile is required');return adapter('network.read',{profileId:id,command:$('network-command').value});});
  async function init(){try{token=(await api('session')).token;await refresh();const profiles=await act('execution.adapter',{operation:{type:'network.profiles'}});$('network-profile').innerHTML=(profiles.profiles||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.id)} · ${esc(p.host)}</option>`).join('')||'<option value="">No device configured</option>';setInterval(()=>{if(!document.hidden&&!$('execution-dialog').open)refresh();},4000);}catch(e){notice(e.message);}}
  init();
})();



