const fs=require('fs'),path=require('path'),art=require('./artwork.js');
const directory=path.join(__dirname,'svg');fs.mkdirSync(directory,{recursive:true});
for(const role of art.roles)fs.writeFileSync(path.join(directory,role+'.svg'),art.svg(role,96)+'\n');
const reactDir=path.join(__dirname,'react');fs.mkdirSync(reactDir,{recursive:true});
const geometry=Object.fromEntries(art.roles.map(role=>[role,{regular:art.inner(role,96),small:art.inner(role,24)}]));
fs.writeFileSync(path.join(reactDir,'NetworkAvatar.tsx'),`// Generated by ../export.cjs from ../artwork.js. Do not edit geometry here.
import * as React from 'react';
import '../avatar.css';
const artwork = ${JSON.stringify(geometry,null,2)} as const;
export type AvatarRole = keyof typeof artwork;
export type AvatarEmotion = ${art.tokens.states.map(s=>`'${s}'`).join(' | ')};
export interface AvatarProps { role: AvatarRole; size?: number; emotion?: AvatarEmotion; active?: boolean; animate?: boolean; label?: string; }
// Presentation only. The host owns focus/activity and returns a transient success to idle.
export function NetworkAvatar({role,size=48,emotion='idle',active=false,animate=true,label}:AvatarProps) {
  return <span data-emotion={emotion} className={active && animate ? 'motion-active' : undefined}>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width={size} height={size} className="cw-avatar" role={label ? 'img' : undefined} aria-label={label} aria-hidden={label ? undefined : true}
      dangerouslySetInnerHTML={{__html: size <= 24 ? artwork[role].small : artwork[role].regular}} />
  </span>;
}
type NamedAvatarProps = Omit<AvatarProps,'role'>;
${art.roles.map(role=>`export const ${role.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join('')}Avatar = (props:NamedAvatarProps) => <NetworkAvatar {...props} role="${role}" />;`).join('\n')}
`);
console.log('Exported '+art.roles.length+' editable SVGs and React components from artwork.js');
